# Comparing segmentations of different tools

## Label structure of the final output files

|              | Label |
|--------------|-------|
| Background   | 0     |
| White Matter | 1     |
| Grey Matter  | 2     |

In [15]:
LABEL_DICT = {"Background": 0, "White Matter": 1, "Grey Matter": 2}

In [2]:
import nibabel as nib
import numpy as np
from pathlib import Path

In [3]:
gt_label = "/home/lmahler/data/fb9364/fb9364_seg/itksnap24_09/ribbon.nii"
fast_seg = "/home/lmahler/val_out/test/fb9364/fast/fb9364_seg_seg.nii.gz"

In [4]:
gt_vol = nib.load(Path(gt_label))

In [5]:
fast_vol = nib.load(Path(fast_seg))

In [9]:
print(fast_vol.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 16384
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 352 352 256   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int32
bitpix          : 32
slice_start     : 0
pixdim          : [1.         0.59943175 0.5994318  0.59999996 1.         1.
 1.         1.        ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'6.0.4:ddd0a010'
aux_file        : b''
qform_code      : unknown
sform_code      : aligned
quatern_b       : -0.99904823
quatern_c       : -0.0
quatern_d       : -0.0
qoffset_x       : -106.964424
qoffse

In [19]:
np.unique(fast_vol.get_fdata())


array([0., 1., 2., 3.])

In [20]:
np.unique(gt_vol.get_fdata())

array([ 0.,  2.,  3., 41., 42.])

In [18]:
gt_vol.get_fdata().shape

(352, 352, 352)

In [21]:
def transform_fsl_labels(data):
    # 0 == bg
    # 1 == csf
    # 2 == grey 
    # 3 == white
    data = np.where(data == 1, 0, data)
    data = np.where(data == 3, 1, data)
    return data

In [22]:
fast_labels = transform_fsl_labels(fast_vol.get_fdata())

In [23]:
np.unique(fast_labels)

array([0., 1., 2.])

In [25]:
def transform_gt_labels(data):
    # 0 == bg
    # 2 == left wm
    # 3 == left gm
    # 41 == right wm
    # 42 == right gm
    
    data = np.where(data == 2, 1, data)
    data = np.where(data == 3, 2, data)
    data = np.where(data == 41, 1, data)
    data = np.where(data == 42, 2, data)
    return data

In [26]:
gt_labels = transform_gt_labels(gt_vol.get_fdata())

In [27]:
np.unique(gt_labels)

array([0., 1., 2.])

In [30]:
fast_labels.shape

(352, 352, 256)